include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - camel_case_types
    - comment_references
    - directives_ordering
    - omit_local_variable_types
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - throw_in_finally
    - type_annotate_public_apis
    - unawaited_futures
